---
# We care when the source, ci/scripts, and ci/tasks code changes.
resources:
  - name: envtoecs-src
    type: git
    source:
      branch: master
      uri: ((git-repositories.envtoecs-uri))
      private_key: ((git-repositories.envtoecs-key))

  - name: envtoecs-image
    type: docker-image
    source:
      repository: 7factor/env-to-ecs
      username: ((dockerhub.username))
      password: ((dockerhub.password))

jobs:

  #####################
  ##     TESTING     ##
  #####################

  - name: unit-tests
    serial_groups: [unit-tests]
    plan:
      - get: envtoecs-src
        trigger: true
      - task: unit-tests
        file: envtoecs-src/ci/tasks/unit-tests.yml

  - name: int-tests
    serial_groups: [int-tests]
    plan:
      - get: envtoecs-src
        trigger: true
      - task: int-tests
        file: envtoecs-src/ci/tasks/int-tests.yml

  ####################
  ##     DEPLOY     ##
  ####################

  - name: dockerhub-deploy
    serial_groups: [unit-tests, int-tests]
    plan:
      - get: envtoecs-src
        trigger: true
        passed: [unit-tests, int-tests]
      - put: envtoecs-image
        params:
          tag_as_latest: false
          build: envtoecs-src
          dockerfile: envtoecs-src/Dockerfile
          additional_tags: envtoecs-src/.git/short_ref
        get_params:
          skip_download: true
