---
# We care when the source, ci/scripts, and ci/tasks code changes.
resources:
  - name: dotenvtoecs-src
    type: git
    source:
      branch: master
      uri: ((git-repositories.dotenvtoecs-uri))
      private_key: ((git-repositories.dotenvtoecs-key))

  - name: dotenvtoecs-image
    type: docker-image
    source:
      repository: 7factor/dotenv-to-ecs

jobs:

  #####################
  ##     TESTING     ##
  #####################

  - name: unit-tests
    serial_groups: [staging]
    plan:
      - get: dotenvtoecs-src
        trigger: true
      - task: unit-tests
        file: dotenvtoecs-src/ci/tasks/unit-tests.yml

  #####################
  ##     BUILD       ##
  #####################

  - name: build-rc
    serial_groups: [staging]
    plan:
      - get: dotenvtoecs-src
        trigger: true
        passed: [unit-tests]
      - put: dotenvtoecs-image
        params:
          tag_as_latest: false
          build: dotenvtoecs-src
          dockerfile: dotenvtoecs-src/env/Dockerfile
          additional_tags: dotenvtoecs-src/.git/short_ref
        get_params:
          skip_download: true
