---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: instrumentisto/glide
    tag: 0.13

inputs:
- name: envtoecs-src

run:
  path: sh
  args:
  - -exc
  - |
    ./ci/scripts/int_tests.sh
  dir: envtoecs-src
